url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: KF Labs
email: mfa@wp.pl
description: "Applying Natural Language Processing to real world problems and business challanges."


# Team names, titles and social links
people:
- name: Michal Falenski
  pic: 1
  position: Software Architect
  social:
    - title: twitter
      url: https://twitter.com/fala133
    - title: stack-overflow
      url: https://stackoverflow.com/users/3323967/fala
    - title: linkedin
      url: https://www.linkedin.com/in/falenski/
    - title: github
      url: https://github.com/fala13

- name: Enrica Troiano
  pic: 2
  position: NLP Researcher
  social:
    - title: Univerisity page
      url: https://www.ims.uni-stuttgart.de/en/institute/team/Troiano/

- name: Elie Khoury
  pic: 3
  position: Enterprise Architect
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/eliekhoury/
    - title: github
      url: https://github.com/slonoko

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/kf-labs

# Postal address (add as many lines as necessary)
address:
  - line: There is no presence like the online presence.

# Build settings
markdown: kramdown
permalink: pretty
